name: test suite
on: [push]
image: ubuntu-latest
jobs:

  lint:
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0 # match .tool-versions file
      - name: install
        run: npm ci
      - name: tests
        run: npm run lint

  test:
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0 # match .tool-versions file
      - name: install
        run: npm ci
      - name: tests
        run: npm run test
